/**
 * TokenomicsCards — 4 illustrated cards summarising the supply allocation.
 *
 * Replaces the old TokenomicsLockBadges + standalone BurnCounter pair
 * with a unified visual block that fits below the existing donut chart.
 *
 * Layout per card (3:4 portrait):
 *
 *   ┌─────────────────────────┐
 *   │  TITLE (satirical)      │  ← top 1/3
 *   │  55%                    │     · kicker ("ΔΣ-XX")
 *   │  status badge           │     · % in mono
 *   ├─────────────────────────┤     · sub-text (lock state / terms)
 *   │                         │
 *   │   IA illustration       │  ← bottom 2/3
 *   │   (full-bleed)          │     served from /api/assets/tokenomics_*.jpg
 *   │                         │
 *   └─────────────────────────┘
 *
 * The 4 cards:
 *   1. Public  55%   — "Le Peuple Algorithmique"   (silhouette crowd)
 *   2. Treasury 30%  — "Le Coffre Scellé"           (vault dial + ΔΣ)
 *   3. Team    15%   — "Les Ombres du Conseil"     (anonymous overcoats)
 *   4. Burn    🔥    — "Le Feu Rituel"              (ceremonial brazier)
 *
 * Hero images come from /api/assets/tokenomics_<id>.jpg (committed JPGs
 * generated by backend/scripts/generate_email_asset.py --all-tokenomics
 * via gpt-image-1, ~30-50 KB each, 960×540 16:9 already-cropped).
 *
 * Card 4 (Burn) is a hybrid: top section reads from the burn aggregate
 * /api/treasury/burns; the bottom illustration is static. Empty state
 * shows a placeholder copy ("Phase 1 active · First burn at J+30").
 */

import React, { useEffect, useState } from "react";
import axios from "axios";
import { Link } from "react-router-dom";
import {
  Lock,
  ExternalLink,
  Loader2,
  Users,
  Vault,
  Eye,
  Flame,
} from "lucide-react";
import { useI18n } from "@/i18n/I18nProvider";
import { URLS } from "@/lib/launchPhase";

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;
const TOTAL_SUPPLY = 1_000_000_000;

// ---------------------------------------------------------------------
// Burn data fetch
// ---------------------------------------------------------------------
interface BurnSummary {
  total_burned_tokens: number;
  burn_count: number;
  last_burn_at: string | null;
  last_burn_signature: string | null;
}

function formatBurnPercent(burned: number): string {
  if (!burned) return "0%";
  const pct = (burned / TOTAL_SUPPLY) * 100;
  if (pct < 0.01) return "<0.01%";
  if (pct < 1) return `${pct.toFixed(2)}%`;
  return `${pct.toFixed(1)}%`;
}

// ---------------------------------------------------------------------
// Card model
// ---------------------------------------------------------------------
type LockState = "open" | "locked" | "pending";

interface CardConfig {
  id: "public" | "treasury" | "shadows" | "burn";
  /** ΔΣ-XX dossier code shown as kicker. */
  code: string;
  /** Image filename (without extension). Served from /api/assets. */
  imageSlug: string;
  /** Lucide icon shown next to the title. */
  // eslint-disable-next-line
  Icon: any;
  /** Resolves the right-side data slot at render time. */
  metric: () => {
    valueLabel: string; // big number (% or token count)
    state: LockState;
    stateText: string;
    lockUrl?: string;
  };
}

// ---------------------------------------------------------------------
// Card subcomponent
// ---------------------------------------------------------------------
const StateChip: React.FC<{ state: LockState; label: string }> = ({
  state,
  label,
}) => {
  const styles =
    state === "locked"
      ? "border-[#33FF33]/40 bg-[#33FF33]/10 text-[#33FF33]"
      : state === "pending"
        ? "border-[#F59E0B]/40 bg-[#F59E0B]/10 text-[#F59E0B]"
        : "border-foreground/15 bg-foreground/5 text-foreground/70";
  return (
    <span
      className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[9px] font-mono uppercase tracking-[0.2em] border ${styles}`}
    >
      {state !== "open" && <Lock size={9} />}
      {label}
    </span>
  );
};

interface IllustratedCardProps {
  cfg: CardConfig;
  i18nKey: string;
}

const IllustratedCard: React.FC<IllustratedCardProps> = ({ cfg, i18nKey }) => {
  const { t } = useI18n();
  const m = cfg.metric();
  const heroUrl = `${BACKEND_URL}/api/assets/${cfg.imageSlug}.jpg`;
  const Icon = cfg.Icon;

  return (
    <article
      className="group relative flex flex-col rounded-md border border-foreground/15 bg-foreground/[0.03] overflow-hidden hover:border-foreground/30 transition-all"
      data-testid={`tokenomics-card-${cfg.id}`}
      data-card-state={m.state}
    >
      {/* Top 1/3 — text block */}
      <div className="px-4 sm:px-5 py-4 sm:py-5 flex flex-col gap-2">
        <div className="flex items-center justify-between gap-2">
          <span className="font-mono text-[9px] uppercase tracking-[0.3em] text-foreground/50">
            {cfg.code}
          </span>
          <Icon size={13} className="text-foreground/55" />
        </div>
        <h3
          className="text-[11px] sm:text-xs font-semibold tracking-wide leading-snug text-foreground"
          data-testid={`tokenomics-card-${cfg.id}-title`}
        >
          {t(`tokenomics.cards.${i18nKey}.title`) as string}
        </h3>
        <div className="flex items-baseline gap-2 flex-wrap">
          <span
            className="font-mono text-2xl sm:text-3xl font-semibold tabular text-foreground"
            data-testid={`tokenomics-card-${cfg.id}-value`}
          >
            {m.valueLabel}
          </span>
          <StateChip state={m.state} label={m.stateText} />
        </div>
        {m.lockUrl && (
          <a
            href={m.lockUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1 text-[10px] font-mono uppercase tracking-[0.2em] text-[#2DD4BF] hover:underline self-start"
            data-testid={`tokenomics-card-${cfg.id}-lock-link`}
          >
            Lock proof <ExternalLink size={9} />
          </a>
        )}
      </div>

      {/* Bottom 2/3 — illustration */}
      <div
        className="relative aspect-[16/10] overflow-hidden border-t border-foreground/10 bg-black"
        data-testid={`tokenomics-card-${cfg.id}-image`}
      >
        <img
          src={heroUrl}
          alt={t(`tokenomics.cards.${i18nKey}.alt`) as string}
          loading="lazy"
          className="absolute inset-0 w-full h-full object-cover transition-transform duration-500 group-hover:scale-[1.03]"
        />
        {/* Subtle bottom gradient so any future overlay is more readable */}
        <div className="absolute inset-x-0 bottom-0 h-12 bg-gradient-to-t from-black/55 to-transparent pointer-events-none" />
      </div>
    </article>
  );
};

// ---------------------------------------------------------------------
// Public component
// ---------------------------------------------------------------------
export function TokenomicsCards() {
  const { t } = useI18n();
  const [burn, setBurn] = useState<BurnSummary | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await axios.get<BurnSummary>(`${API}/treasury/burns`);
        if (!cancelled) setBurn(res.data);
      } catch {
        if (!cancelled) {
          setBurn({
            total_burned_tokens: 0,
            burn_count: 0,
            last_burn_at: null,
            last_burn_signature: null,
          });
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const burnReady = burn !== null;
  const burned = burn?.total_burned_tokens || 0;

  const cards: CardConfig[] = [
    {
      id: "public",
      code: "ΔΣ-55",
      imageSlug: "tokenomics_public",
      Icon: Users,
      metric: () => ({
        valueLabel: "55%",
        state: "open",
        stateText: t("tokenomics.cards.public.terms") as string,
      }),
    },
    {
      id: "treasury",
      code: "ΔΣ-30",
      imageSlug: "tokenomics_treasury",
      Icon: Vault,
      metric: () => {
        const url = URLS.treasuryLock;
        return {
          valueLabel: "30%",
          state: url ? "locked" : "pending",
          stateText: url
            ? (t("tokenomics.cards.treasury.locked") as string)
            : (t("tokenomics.cards.lockPending") as string),
          lockUrl: url || undefined,
        };
      },
    },
    {
      id: "shadows",
      code: "ΔΣ-15",
      imageSlug: "tokenomics_shadows",
      Icon: Eye,
      metric: () => {
        const url = URLS.teamLock;
        return {
          valueLabel: "15%",
          state: url ? "locked" : "pending",
          stateText: url
            ? (t("tokenomics.cards.shadows.locked") as string)
            : (t("tokenomics.cards.lockPending") as string),
          lockUrl: url || undefined,
        };
      },
    },
    {
      id: "burn",
      code: "ΔΣ-FIRE",
      imageSlug: "tokenomics_burn",
      Icon: Flame,
      metric: () => {
        if (!burnReady) {
          return {
            valueLabel: "—",
            state: "open" as LockState,
            stateText: t("common.loading") as string,
          };
        }
        if (burned === 0) {
          return {
            valueLabel: "0%",
            state: "open" as LockState,
            stateText: t("tokenomics.cards.burn.empty") as string,
          };
        }
        return {
          valueLabel: formatBurnPercent(burned),
          state: "open" as LockState,
          stateText: `${burned.toLocaleString()} ${t("tokenomics.cards.burn.tokens") as string}`,
        };
      },
    },
  ];

  return (
    <div
      className="mt-12 pt-10 border-t border-border/50"
      data-testid="tokenomics-cards"
    >
      <div className="flex items-baseline justify-between mb-5 gap-3 flex-wrap">
        <h3 className="text-sm font-semibold tracking-wide text-foreground">
          {t("tokenomics.cards.sectionTitle") as string}
        </h3>
        {burnReady && burn?.last_burn_at && (
          <a
            href={URLS.solscanTx(burn.last_burn_signature || "")}
            target="_blank"
            rel="noopener noreferrer"
            className="font-mono text-[10px] uppercase tracking-[0.2em] text-foreground/55 hover:text-foreground transition-colors"
          >
            🔥 {t("tokenomics.cards.burn.lastBurn") as string}:{" "}
            {new Date(burn.last_burn_at).toISOString().slice(0, 10)}
          </a>
        )}
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {cards.map((c) => (
          <IllustratedCard key={c.id} cfg={c} i18nKey={c.id} />
        ))}
      </div>

      {/* Cross-link to the standalone /transparency page */}
      <div className="mt-6 text-center">
        <Link
          to="/transparency"
          className="inline-block font-mono text-[11px] uppercase tracking-[0.2em] text-muted-foreground hover:text-foreground transition-colors"
          data-testid="tokenomics-cards-transparency-link"
        >
          {t("tokenomics.cards.transparencyLink") as string} →
        </Link>
      </div>
    </div>
  );
}

export default TokenomicsCards;
