"""Mission emails (Sprint 21).

Resend-powered transactional email for every new ``mission_participations``
row. Bilingual (FR/EN) per the visitor's locale, includes the mission
illustration generated by ``mission_illustrations``.

The sender (``SENDER_EMAIL``) and Resend key (``RESEND_API_KEY``) come
from existing env vars — no new secrets required.

Failure mode is intentionally **soft**: a failed send marks the row
with ``email_last_error`` but does NOT raise to the API caller (the
participation is still persisted, the admin can re-send later).
"""

from __future__ import annotations

from typing import Any, Dict, Optional

import resend

from core import mission_illustrations, mission_participations
from core.config import (
    PUBLIC_BASE_URL,
    RESEND_API_KEY,
    SENDER_EMAIL,
    logger,
)

# ---------------------------------------------------------------------
# i18n strings (per-mission, per-locale)
# ---------------------------------------------------------------------
_BRAND = "Cabinet ΔΣ · DEEPOTUS"

# (subject, headline, body, cta_label) tuples per mission × locale.
# Kept here (NOT in the React i18n bundle) because email copy is
# slightly different from on-site copy (longer, friendlier).
_EMAIL_TEMPLATES: Dict[str, Dict[str, Dict[str, str]]] = {
    "infiltration": {
        "fr": {
            "subject": "Infiltration confirmée — Cabinet ΔΣ",
            "headline": "Opération 001 — Infiltration acquise",
            "body": (
                "Agent, votre engagement sur l'opération <strong>INFILTRATION</strong> "
                "est enregistré. Vous recevrez les instructions classifiées par "
                "l'antenne Telegram dès la prochaine fenêtre opérationnelle."
            ),
            "cta_label": "Accéder à l'antenne Telegram",
        },
        "en": {
            "subject": "Infiltration confirmed — Cabinet ΔΣ",
            "headline": "Operation 001 — Infiltration acknowledged",
            "body": (
                "Agent, your commitment to <strong>OPERATION INFILTRATION</strong> "
                "is recorded. Classified briefing will reach you via the Telegram "
                "channel at the next operational window."
            ),
            "cta_label": "Open Telegram channel",
        },
    },
    "liquidity": {
        "fr": {
            "subject": "Protocol Liquidity — éligibilité confirmée",
            "headline": "Protocol 002 — Liquidity enregistrée",
            "body": (
                "Votre participation au protocole <strong>LIQUIDITY</strong> est verrouillée. "
                "Le snapshot on-chain vérifiera votre solde au moment du tirage — "
                "aucun formulaire supplémentaire requis."
            ),
            "cta_label": "Vérifier les règles",
        },
        "en": {
            "subject": "Protocol Liquidity — eligibility confirmed",
            "headline": "Protocol 002 — Liquidity logged",
            "body": (
                "Your commitment to <strong>PROTOCOL LIQUIDITY</strong> is locked. "
                "The on-chain snapshot will verify your balance at draw time — "
                "no extra form required."
            ),
            "cta_label": "Check the rules",
        },
    },
    "amplification": {
        "fr": {
            "subject": "Directive Amplification — confirmée",
            "headline": "Directive 003 — Amplification active",
            "body": (
                "L'émetteur du Cabinet a reçu votre engagement pour la directive "
                "<strong>AMPLIFICATION</strong>. Votre relais sera noté sur la "
                "prochaine fenêtre de propagation."
            ),
            "cta_label": "Ouvrir le canal de signal",
        },
        "en": {
            "subject": "Directive Amplification — confirmed",
            "headline": "Directive 003 — Amplification active",
            "body": (
                "The Cabinet broadcaster has registered your commitment to "
                "<strong>DIRECTIVE AMPLIFICATION</strong>. Your relay will be logged "
                "on the next propagation window."
            ),
            "cta_label": "Open the signal channel",
        },
    },
    "archive": {
        "fr": {
            "subject": "Accès Archive — dossier enregistré",
            "headline": "Archive 004 — accès consigné",
            "body": (
                "Votre dossier <strong>ARCHIVE</strong> est enregistré. Les fragments "
                "classifiés vous seront distribués séquentiellement — surveillez votre "
                "boîte de réception."
            ),
            "cta_label": "Consulter l'index",
        },
        "en": {
            "subject": "Archive access — dossier filed",
            "headline": "Archive 004 — access logged",
            "body": (
                "Your <strong>ARCHIVE</strong> dossier is filed. Classified fragments "
                "will be released sequentially — watch your inbox."
            ),
            "cta_label": "View the index",
        },
    },
    "signal": {
        "fr": {
            "subject": "Signal capté — transmission entrante",
            "headline": "Signal 005 — transmission entrante",
            "body": (
                "Votre relais sur <strong>SIGNAL</strong> est confirmé. La prochaine "
                "répétition transmettra ses coordonnées par cette même voie."
            ),
            "cta_label": "Synchroniser le canal",
        },
        "en": {
            "subject": "Signal acquired — transmission incoming",
            "headline": "Signal 005 — transmission incoming",
            "body": (
                "Your relay on <strong>SIGNAL</strong> is confirmed. The next pulse "
                "will share its coordinates through this very channel."
            ),
            "cta_label": "Sync the channel",
        },
    },
    "future_06": {
        "fr": {
            "subject": "Opération 006 — fichier scellé",
            "headline": "Opération 006 — fichier scellé",
            "body": (
                "Votre demande a été ajoutée à la liste prioritaire. Le scellé sera "
                "levé lorsque l'opération sera déclassifiée — vous serez le premier averti."
            ),
            "cta_label": "Garder un œil sur le Cabinet",
        },
        "en": {
            "subject": "Operation 006 — file sealed",
            "headline": "Operation 006 — file sealed",
            "body": (
                "Your request has been added to the priority list. The seal will be "
                "lifted when the operation is declassified — you'll be the first to know."
            ),
            "cta_label": "Keep an eye on the Cabinet",
        },
    },
}


def _public_image_url(mission_id: str) -> str:
    """Build an absolute URL Resend can fetch."""
    return mission_illustrations.get_mission_image_public_url(
        mission_id, base_url=PUBLIC_BASE_URL or ""
    )


def _render_html(
    *,
    mission_id: str,
    locale: str,
    cta_url: str,
) -> str:
    """Build the inline-styled HTML body.

    Inline styles only — Outlook/Gmail web friendly. The illustration
    is referenced as a remote URL, not embedded as cid: (simpler, and
    the Vercel CDN serves the PNG fast).
    """
    tpl = _EMAIL_TEMPLATES[mission_id][locale]
    img_url = _public_image_url(mission_id)
    bg = "#0B0E14"
    fg = "#F6F2EA"
    muted = "#9CA3AF"
    accent = "#F59E0B"
    return f"""\
<!doctype html>
<html><body style="margin:0;background:{bg};color:{fg};font-family:'IBM Plex Sans',sans-serif;">
  <table role="presentation" cellspacing="0" cellpadding="0" width="100%" style="background:{bg};">
    <tr><td align="center" style="padding:32px 16px;">
      <table role="presentation" cellspacing="0" cellpadding="0" width="560" style="max-width:560px;width:100%;background:#11151D;border:1px solid rgba(245,242,234,0.10);border-radius:14px;overflow:hidden;">
        <tr><td>
          <img src="{img_url}" alt="" width="560" style="display:block;width:100%;height:auto;" />
        </td></tr>
        <tr><td style="padding:28px 28px 8px 28px;">
          <div style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.28em;color:{accent};text-transform:uppercase;">{_BRAND}</div>
          <h1 style="font-family:'Space Grotesk','IBM Plex Sans',sans-serif;font-size:24px;line-height:1.2;margin:12px 0 0 0;color:{fg};">{tpl['headline']}</h1>
        </td></tr>
        <tr><td style="padding:14px 28px 8px 28px;">
          <p style="font-size:15px;line-height:1.55;color:{fg};opacity:.86;margin:0;">{tpl['body']}</p>
        </td></tr>
        <tr><td style="padding:22px 28px 28px 28px;">
          <a href="{cta_url}" style="display:inline-block;padding:12px 18px;background:{accent};color:#0B0E14;text-decoration:none;font-family:'IBM Plex Sans',sans-serif;font-weight:600;border-radius:8px;letter-spacing:.02em;">{tpl['cta_label']}</a>
        </td></tr>
        <tr><td style="padding:8px 28px 24px 28px;border-top:1px solid rgba(245,242,234,0.08);">
          <p style="font-family:'IBM Plex Mono',monospace;font-size:11px;line-height:1.6;color:{muted};margin:14px 0 0 0;">
            deepotus.xyz · Cabinet ΔΣ · Aucun rendement promis — DYOR<br/>
            Si vous n'êtes pas à l'origine de cette inscription, ignorez ce message.
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>
"""


async def send_mission_email(
    *,
    participation_id: str,
    mission_id: str,
    to_email: str,
    locale: str,
    cta_url: str,
) -> Dict[str, Any]:
    """Send the participation email. Updates the participation row
    accordingly. Returns ``{ok, message_id?, error?}``.

    NEVER raises — the caller (API or webhook) treats the send as
    best-effort.
    """
    if not RESEND_API_KEY:
        await mission_participations.mark_email_failed(
            participation_id, error="resend_not_configured"
        )
        return {"ok": False, "error": "resend_not_configured"}
    if mission_id not in _EMAIL_TEMPLATES:
        await mission_participations.mark_email_failed(
            participation_id, error=f"unknown_mission_{mission_id}"
        )
        return {"ok": False, "error": f"unknown_mission_{mission_id}"}
    loc = locale if locale in ("fr", "en") else "fr"
    subj = _EMAIL_TEMPLATES[mission_id][loc]["subject"]
    html = _render_html(mission_id=mission_id, locale=loc, cta_url=cta_url)
    try:
        resp = resend.Emails.send({
            "from": SENDER_EMAIL,
            "to": [to_email],
            "subject": subj,
            "html": html,
        })
        message_id = None
        if isinstance(resp, dict):
            message_id = resp.get("id")
        await mission_participations.mark_email_sent(
            participation_id, message_id=message_id
        )
        logger.info(
            "[mission_emails] sent mission=%s to=%s id=%s",
            mission_id, to_email, message_id,
        )
        return {"ok": True, "message_id": message_id}
    except Exception as exc:  # noqa: BLE001
        logger.exception("[mission_emails] send failed for mission=%s", mission_id)
        await mission_participations.mark_email_failed(
            participation_id, error=str(exc)
        )
        return {"ok": False, "error": str(exc)}


__all__ = ["send_mission_email"]
